name: Python Tests

on:
  push:
    branches:
        - 'issue2'
        - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2  # Checks out the repository
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Choose the Python version you want to use
    - name: Install dependencies
      run: pip install -r requirements.txt  # Install your project dependencies
      pip install pytest-cov  # Install pytest-cov plugin for coverage reporting
    - name: Run tests with coverage
        run: pytest --cov=.
